### PR TITLE
Improve lobby menu

### LINKED ISSUE #154: Improve the lobby screen
**Description**
The lobby menu needs to be improved. Players are confused about which card is theirs and wether or not they have joined.

**Subtasks**
- [x] Flash the players card when they press a button
- [x] Maybe tint the cards with the player color? (Should player actually be color coded)
- [x] Maybe show an icon of what input device the player is using (keyboard/gamepad)
- [x] Have a way to un-join a device?
- [x] Don't start the game when joining with the start button

### PR DESCRIPTION
**Pull request by smeas**
Closes #154 

**List of changes**  
- Cards have player color
- Flash card when join button is pressed
- Can only join with a/space
- Can un-join/go back with b/escape
- Add controller type icons
- Destroy interactable/pickup highlights when player is destroyed
- Add space as an alternative submit button

**Additional context**  
image

### CODE REVIEW

**Review by DreamingJohnny — COMMENTED** [review]
I've only tried it so far and I'm going to begin reading your code now.
But I have a small suggestion already: I think that the "flash" on the player field, signaling that you have already applied, should be longer.
I think the flash should have twice the duration, and the color change should be more drastic as well.

**Review by DreamingJohnny — APPROVED** [review]
Very nice!
Looks, clean, proper & logical.

**Review by MrJackey — COMMENTED** [review]
Mostly good, not sure if I'm supposed to be able to enter the lobby from main menu with space and using a gamepad to enter the lobby (Button South) places that person as player 1.

**Review by MrJackey — APPROVED** [review]
:shipit:

**Pull request merged**
